In [1]:
import torch
import numpy as np

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [4]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [5]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [6]:
w = torch.randn(2, 3, requires_grad=True) # 2, 3 bcz i have to predict apples and oranges one row of weights for apples and one for oranges
b = torch.randn(2, requires_grad=True) # 2  biases one for apples and one for oranges

In [7]:
def model(input):
  preds = input @ w.t() + b
  return preds

In [9]:
preds = model(inputs)
#print(preds)
#print(targets)

tensor([[133.1160, 139.8363],
        [171.6099, 179.6326],
        [222.9986, 236.0357],
        [126.6544, 130.3893],
        [164.4378, 173.6293]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [19]:
def mse(pred, target):
  diff = pred - target
  return torch.sum(diff * diff) / diff.numel()

In [20]:
loss = mse(preds, targets)
print(loss)

tensor(7308.2373, grad_fn=<DivBackward0>)


In [23]:
loss.backward() #computing gradient of loss

In [26]:
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor([[ 0.7566,  1.1831,  0.0014],
        [ 0.7349,  1.2872, -0.0221]], requires_grad=True)
tensor([[7567.3628, 7494.8857, 4663.9609],
        [6902.5713, 6933.1289, 4258.1953]])
tensor([-1.4461,  0.8939], requires_grad=True)
tensor([87.5634, 79.9047])


In [27]:
w.grad = w.grad * 1e-5       #this is the learning rate which will reduce our gradient weghts it takes smaller steps

In [28]:
print(w.grad)

tensor([[0.0757, 0.0749, 0.0466],
        [0.0690, 0.0693, 0.0426]])


In [22]:
### Train Gradient Descent to reduce the loss

In [75]:
for i in range(20): #number of epochs
   preds = model(inputs)
   loss = mse(preds, targets)
   loss.backward() #calculating gradient

   with torch.no_grad():  # we are saying torch to not track these computations
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

    w.grad.zero_() #if i don't assign zero to weights then on next epoch these grads add in new calculated grads
    b.grad.zero_()

In [76]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(1.3389, grad_fn=<DivBackward0>)


In [77]:
print(preds)
print(targets)

tensor([[ 56.9893,  70.5418],
        [ 81.7942,  99.8736],
        [119.9098, 134.3987],
        [ 21.4419,  37.4067],
        [100.7057, 117.6991]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
