In [7]:
import torch
import torch.nn as nn
import numpy as np

In [8]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [11]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0302,  0.2071, -0.3835],
        [ 0.3639, -0.0910, -0.4021]], requires_grad=True)
Parameter containing:
tensor([ 0.3059, -0.3944], requires_grad=True)


In [12]:
from torch.utils.data import TensorDataset

In [15]:
train_TD = TensorDataset(inputs, targets)

for xT, yT in train_TD:
  print(xT)
  print(yT)
  break

tensor([73., 67., 43.])
tensor([56., 70.])


In [16]:
from torch.utils.data import DataLoader

In [17]:
batch_size = 5
train_DL = DataLoader(train_TD, batch_size, shuffle=True)

In [23]:
for train in train_DL:
  print(train)
  break

[tensor([[ 69.,  96.,  70.],
        [ 91.,  87.,  65.],
        [ 91.,  88.,  64.],
        [ 74.,  66.,  43.],
        [102.,  43.,  37.]]), tensor([[103., 119.],
        [ 80., 102.],
        [ 81., 101.],
        [ 57.,  69.],
        [ 22.,  37.]])]


In [27]:
preds = model(inputs)
print(preds)
print(targets)

tensor([[ -0.1019,   2.7799],
        [ -3.2621,  -1.0261],
        [  8.4444,  -4.2564],
        [ -1.8944,  17.9303],
        [ -4.5715, -12.1727],
        [ -0.2787,   3.2348],
        [ -3.8527,  -1.3372],
        [  8.0911,  -4.2946],
        [ -1.7175,  17.4753],
        [ -4.9852, -12.9387],
        [ -0.6925,   2.4688],
        [ -3.4390,  -0.5712],
        [  9.0350,  -3.9453],
        [ -1.4806,  18.6963],
        [ -4.3946, -12.6277]], grad_fn=<AddmmBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


In [24]:
import torch.nn.functional as F

In [28]:
loss_fn = F.mse_loss

In [29]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(8589.9082, grad_fn=<MseLossBackward0>)


In [30]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

**Training to find best weights means reducing loss**

In [41]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
  for epoch in range(num_epochs):
    #train with batches of data
    for xT, yT in train_dl:
      # 1. Generate predictions
      pred = model(xT)

      # 2. Calculate loss
      loss = loss_fn(pred, yT)

      # 3. Compute gradients
      loss.backward()

      # 4. Update parameters using gradients
      opt.step()

      # 5. Reset the gradients to zero
      opt.zero_grad()

    if (epoch+1) % 10 == 0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))


In [ ]:
print(fit(10, model, loss_fn, opt, train_DL))

In [ ]:
preds = model(inputs)
print(preds)
print(targets)

In [40]:
model(torch.tensor([[91.,  88.,  64.]]))

tensor([[79.8912, 98.0562]], grad_fn=<AddmmBackward0>)